import type {
  Organization,
  Customer,
  Product,
  Supplier,
  RawMaterial,
  Origin,
  RiskAssessment,
  DueDiligenceStatement,
} from "@/types"

// Mock Organizations
export const mockOrganizations: Organization[] = [
  {
    id: "org-1",
    name: "Green Coffee Exporters Ltd",
    address: "123 Coffee Street, São Paulo, Brazil",
    contact_person: "Maria Silva",
    email: "maria@greencoffee.com",
    phone: "+55 11 9999-8888",
    registration_number: "BR123456789",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "org-2",
    name: "Sustainable Cocoa Co.",
    address: "456 Plantation Road, Accra, Ghana",
    contact_person: "Kwame Asante",
    email: "kwame@sustainablecocoa.com",
    phone: "+233 20 123-4567",
    registration_number: "GH987654321",
    created_at: "2024-01-16T11:00:00Z",
    updated_at: "2024-01-16T11:00:00Z",
  },
]

// Mock Customers
export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "John Smith",
    company: "European Coffee Roasters",
    address: "789 Roasting Ave, Amsterdam, Netherlands",
    email: "john@euroroasters.com",
    phone: "+31 20 555-0123",
    country: "Netherlands",
    created_at: "2024-01-17T09:00:00Z",
    updated_at: "2024-01-17T09:00:00Z",
  },
  {
    id: "cust-2",
    name: "Sophie Dubois",
    company: "French Chocolate Masters",
    address: "321 Chocolat Boulevard, Lyon, France",
    email: "sophie@chocolatemasters.fr",
    phone: "+33 4 7777-8888",
    country: "France",
    created_at: "2024-01-18T14:00:00Z",
    updated_at: "2024-01-18T14:00:00Z",
  },
]

// Mock Products
export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Premium Arabica Coffee Beans",
    description: "High-quality arabica coffee beans from sustainable farms",
    category: "Coffee",
    hs_code: "0901.11",
    origin_country: "Brazil",
    supplier_id: "supp-1",
    risk_level: "low",
    certification: "Rainforest Alliance, Fair Trade",
    created_at: "2024-01-19T08:00:00Z",
    updated_at: "2024-01-19T08:00:00Z",
  },
  {
    id: "prod-2",
    name: "Organic Cocoa Beans",
    description: "Certified organic cocoa beans from Ghana",
    category: "Cocoa",
    hs_code: "1801.00",
    origin_country: "Ghana",
    supplier_id: "supp-2",
    risk_level: "medium",
    certification: "Organic, UTZ Certified",
    created_at: "2024-01-20T12:00:00Z",
    updated_at: "2024-01-20T12:00:00Z",
  },
]

// Mock Suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: "supp-1",
    name: "Santos Coffee Farms",
    company_registration: "BR-FARM-001",
    address: "Rural Area, Santos, São Paulo, Brazil",
    country: "Brazil",
    contact_person: "Carlos Santos",
    email: "carlos@santoscoffee.com",
    phone: "+55 13 8888-7777",
    business_type: "Coffee Farm",
    verification_status: "verified",
    certifications: "Rainforest Alliance, Fair Trade",
    risk_level: "low",
    last_audit_date: "2024-01-10",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "supp-2",
    name: "Ashanti Cocoa Cooperative",
    company_registration: "GH-COOP-002",
    address: "Kumasi Region, Ghana",
    country: "Ghana",
    contact_person: "Akosua Mensah",
    email: "akosua@ashanticocoa.com",
    phone: "+233 32 444-5555",
    business_type: "Cooperative",
    verification_status: "pending",
    certifications: "Organic, UTZ Certified",
    risk_level: "medium",
    last_audit_date: "2023-12-15",
    created_at: "2024-01-12T15:00:00Z",
    updated_at: "2024-01-12T15:00:00Z",
  },
]

// Mock Raw Materials
export const mockRawMaterials: RawMaterial[] = [
  {
    id: "raw-1",
    name: "Arabica Coffee Cherries",
    type: "Coffee",
    origin_location: "Santos Region, São Paulo, Brazil",
    coordinates: "-23.9608, -46.3331",
    harvest_date: "2024-01-05",
    supplier_id: "supp-1",
    volume: 5000,
    unit: "kg",
    sustainability_certificate: "Rainforest Alliance RA-2024-001",
    risk_assessment: "low",
    created_at: "2024-01-05T06:00:00Z",
    updated_at: "2024-01-05T06:00:00Z",
  },
  {
    id: "raw-2",
    name: "Cocoa Pods",
    type: "Cocoa",
    origin_location: "Ashanti Region, Ghana",
    coordinates: "6.6885, -1.6244",
    harvest_date: "2024-01-08",
    supplier_id: "supp-2",
    volume: 3000,
    unit: "kg",
    sustainability_certificate: "UTZ-2024-002",
    risk_assessment: "medium",
    created_at: "2024-01-08T07:00:00Z",
    updated_at: "2024-01-08T07:00:00Z",
  },
]

// Mock Origins
export const mockOrigins: Origin[] = [
  {
    id: "origin-1",
    location_name: "Santos Coffee Region",
    country: "Brazil",
    region: "São Paulo State",
    coordinates: "-23.9608, -46.3331",
    land_use_type: "Coffee Plantation",
    forest_coverage: 85,
    deforestation_risk: "low",
    protected_area: false,
    indigenous_territory: false,
    land_ownership: "Private",
    monitoring_system: "Satellite + Ground Verification",
    satellite_data_available: true,
    last_verification_date: "2024-01-01",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "origin-2",
    location_name: "Ashanti Cocoa Belt",
    country: "Ghana",
    region: "Ashanti Region",
    coordinates: "6.6885, -1.6244",
    land_use_type: "Cocoa Agroforestry",
    forest_coverage: 65,
    deforestation_risk: "medium",
    protected_area: true,
    indigenous_territory: false,
    land_ownership: "Community",
    monitoring_system: "Community Monitoring",
    satellite_data_available: true,
    last_verification_date: "2023-12-20",
    created_at: "2023-12-20T00:00:00Z",
    updated_at: "2023-12-20T00:00:00Z",
  },
]

// Mock Risk Assessments
export const mockRiskAssessments: RiskAssessment[] = [
  {
    id: "risk-1",
    assessment_name: "Santos Coffee Risk Assessment 2024",
    product_id: "prod-1",
    supplier_id: "supp-1",
    origin_id: "origin-1",
    assessment_date: "2024-01-15",
    assessor_name: "Dr. Ana Rodriguez",
    overall_risk_score: 25,
    deforestation_risk: "low",
    legal_compliance: "compliant",
    environmental_impact: 20,
    social_impact: 15,
    mitigation_measures: "Continue current sustainable practices, increase monitoring frequency",
    follow_up_required: false,
    next_review_date: "2024-07-15",
    status: "approved",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "risk-2",
    assessment_name: "Ashanti Cocoa Risk Assessment 2024",
    product_id: "prod-2",
    supplier_id: "supp-2",
    origin_id: "origin-2",
    assessment_date: "2024-01-20",
    assessor_name: "Prof. Michael Thompson",
    overall_risk_score: 55,
    deforestation_risk: "medium",
    legal_compliance: "under_review",
    environmental_impact: 45,
    social_impact: 35,
    mitigation_measures: "Implement enhanced monitoring, provide additional training to farmers",
    follow_up_required: true,
    next_review_date: "2024-04-20",
    status: "completed",
    created_at: "2024-01-20T14:00:00Z",
    updated_at: "2024-01-20T14:00:00Z",
  },
]

// Mock Due Diligence Statements
export const mockDueDiligenceStatements: DueDiligenceStatement[] = [
  {
    id: "dds-1",
    statement_number: "DDS-2024-001",
    company_name: "Green Coffee Exporters Ltd",
    reporting_period_start: "2024-01-01",
    reporting_period_end: "2024-12-31",
    product_categories: "Coffee, Coffee Products",
    total_volume: 50000,
    volume_unit: "kg",
    countries_of_origin: "Brazil",
    risk_assessment_completed: true,
    mitigation_measures: "Sustainable farming practices, regular audits, farmer training programs",
    monitoring_system: "Satellite monitoring combined with on-ground verification",
    third_party_verification: true,
    declaration_text:
      "We hereby declare that our coffee products comply with EUDR requirements and are deforestation-free.",
    signatory_name: "Maria Silva",
    signatory_position: "CEO",
    signature_date: "2024-01-25",
    status: "submitted",
    submission_date: "2024-01-25",
    created_at: "2024-01-25T09:00:00Z",
    updated_at: "2024-01-25T09:00:00Z",
  },
  {
    id: "dds-2",
    statement_number: "DDS-2024-002",
    company_name: "Sustainable Cocoa Co.",
    reporting_period_start: "2024-01-01",
    reporting_period_end: "2024-12-31",
    product_categories: "Cocoa, Cocoa Products",
    total_volume: 30000,
    volume_unit: "kg",
    countries_of_origin: "Ghana",
    risk_assessment_completed: true,
    mitigation_measures: "Community-based monitoring, agroforestry practices, certification programs",
    monitoring_system: "Community monitoring with satellite data verification",
    third_party_verification: true,
    declaration_text: "We declare our commitment to deforestation-free cocoa supply chains in compliance with EUDR.",
    signatory_name: "Kwame Asante",
    signatory_position: "Managing Director",
    signature_date: "2024-01-28",
    status: "draft",
    submission_date: "",
    created_at: "2024-01-28T11:00:00Z",
    updated_at: "2024-01-28T11:00:00Z",
  },
]
